[package]
name = "worm-macros"
version = "0.0.0"
edition = "2018"
repository = "https://github.com/chuck-flowers/worm"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.24"
quote = "^1.0.7"
syn = "^1.0.53"
