//! Types for representing errors in the worm framework.

pub use crate::executors::SqlExecutionError;

/// Represents all types of errors that can occur in worm.
pub enum WormError {
    /// An error that occurs while executing SQL generated by worm.
    SqlExecutionError(SqlExecutionError),
}

impl From<SqlExecutionError> for WormError {
    fn from(err: SqlExecutionError) -> Self {
        Self::SqlExecutionError(err)
    }
}
